title: Digikoppeling Nationaal Archief
lang: en
description: Beschrijving Grote Berichten Digikoppeling aansluiting Nationaal Archief

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme@v1.1.7

repository: eluinstra/digikoppeling_na

copyright: true

readme_index:
  with_frontmatter: true
