title: Digikoppeling Nationaal Archief
lang: en
description: Beschrijving Grote Berichten Digikoppeling aansluiting Nationaal Archief

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme@v1.1.7

repository: eluinstra/digikoppeling_na

addons_branch: true
edit: true

copyright:
  revision: true

addons:
  - github
  - i18n
  - plugins
  - analytics

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - assets/images/src

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
